/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.rtt.ui.contentassist

import be.kuleuven.rodinia.dsl.rtt.ui.contentassist.AbstractRttDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RttDslProposalProvider extends AbstractRttDslProposalProvider {
}
