/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.rtt.ui.contentassist

import be.kuleuven.rodinia.dsl.rtt.ui.contentassist.AbstractRttStructureProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class RttStructureProposalProvider extends AbstractRttStructureProposalProvider {
}
