/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.rtt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RttStructureUiModule extends be.kuleuven.rodinia.dsl.rtt.ui.AbstractRttStructureUiModule {
	public RttStructureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
