/**
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.rtt.serializer;

import be.kuleuven.rodinia.dsl.rtt.serializer.AbstractRttStructureSemanticSequencer;

@SuppressWarnings("all")
public class RttStructureSemanticSequencer extends AbstractRttStructureSemanticSequencer {
}
