/**
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.rtt.serializer;

import be.kuleuven.rodinia.dsl.rtt.serializer.AbstractRttStructureSyntacticSequencer;

@SuppressWarnings("all")
public class RttStructureSyntacticSequencer extends AbstractRttStructureSyntacticSequencer {
}
