/**
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.datatypes.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class DatatypesQuickfixProvider extends DefaultQuickfixProvider {
}
