/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.datatypes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DatatypesUiModule extends be.kuleuven.rodinia.dsl.datatypes.ui.AbstractDatatypesUiModule {
	public DatatypesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
