/*
 * generated by Xtext
 */
package cz.cuni.mff.d3s.dsl.deeco.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DEECoDslUiModule extends cz.cuni.mff.d3s.dsl.deeco.ui.AbstractDEECoDslUiModule {
	public DEECoDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
