/*
 * generated by Xtext
 */
package cz.cuni.mff.d3s.dsl.deeco.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDEECoDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("cz.cuni.mff.d3s.model.deeco"));
		return result;
	}
}
