/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.datatypes.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import be.kuleuven.rodinia.dsl.datatypes.services.DatatypesGrammarAccess;

public class DatatypesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DatatypesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected be.kuleuven.rodinia.dsl.datatypes.parser.antlr.internal.InternalDatatypesParser createParser(XtextTokenStream stream) {
		return new be.kuleuven.rodinia.dsl.datatypes.parser.antlr.internal.InternalDatatypesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TypeModel";
	}
	
	public DatatypesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DatatypesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
