/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.datatypes.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DatatypesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("be/kuleuven/rodinia/dsl/datatypes/parser/antlr/internal/InternalDatatypes.tokens");
	}
}
