/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.datatypes;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DatatypesUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return be.kuleuven.rodinia.dsl.datatypes.ui.internal.DatatypesActivator.getInstance().getInjector("be.kuleuven.rodinia.dsl.datatypes.Datatypes");
	}
	
}
