/*
* generated by Xtext
*/
package cz.cuni.mff.d3s.dsl.deeco;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DEECoDslStandaloneSetup extends DEECoDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DEECoDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

