/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.rtt;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RttStructureUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return be.kuleuven.rodinia.dsl.rtt.ui.internal.RttStructureActivator.getInstance().getInjector("be.kuleuven.rodinia.dsl.rtt.RttStructure");
	}
	
}
