/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.rtt.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import be.kuleuven.rodinia.dsl.rtt.services.RttStructureGrammarAccess;

public class RttStructureParser extends AbstractContentAssistParser {
	
	@Inject
	private RttStructureGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected be.kuleuven.rodinia.dsl.rtt.ui.contentassist.antlr.internal.InternalRttStructureParser createParser() {
		be.kuleuven.rodinia.dsl.rtt.ui.contentassist.antlr.internal.InternalRttStructureParser result = new be.kuleuven.rodinia.dsl.rtt.ui.contentassist.antlr.internal.InternalRttStructureParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getPackageAccess().getGroup_4(), "rule__Package__Group_4__0");
					put(grammarAccess.getPackageAccess().getGroup_4_3(), "rule__Package__Group_4_3__0");
					put(grammarAccess.getTaskContextAccess().getGroup(), "rule__TaskContext__Group__0");
					put(grammarAccess.getPackageAccess().getNameAssignment_2(), "rule__Package__NameAssignment_2");
					put(grammarAccess.getPackageAccess().getTaskContextsAssignment_4_2(), "rule__Package__TaskContextsAssignment_4_2");
					put(grammarAccess.getPackageAccess().getTaskContextsAssignment_4_3_1(), "rule__Package__TaskContextsAssignment_4_3_1");
					put(grammarAccess.getTaskContextAccess().getNameAssignment_1(), "rule__TaskContext__NameAssignment_1");
					put(grammarAccess.getTaskContextAccess().getNamespaceAssignment_4(), "rule__TaskContext__NamespaceAssignment_4");
					put(grammarAccess.getTaskContextAccess().getTypeAssignment_6(), "rule__TaskContext__TypeAssignment_6");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			be.kuleuven.rodinia.dsl.rtt.ui.contentassist.antlr.internal.InternalRttStructureParser typedParser = (be.kuleuven.rodinia.dsl.rtt.ui.contentassist.antlr.internal.InternalRttStructureParser) parser;
			typedParser.entryRulePackage();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RttStructureGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RttStructureGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
