/**
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.datatypes.ui.contentassist;

import be.kuleuven.rodinia.dsl.datatypes.ui.contentassist.AbstractDatatypesProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class DatatypesProposalProvider extends AbstractDatatypesProposalProvider {
}
