/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.datatypes.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDatatypesValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(be.kuleuven.rodinia.dsl.datatypes.datatypes.DatatypesPackage.eINSTANCE);
		return result;
	}
}
