/*
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.rtt.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import be.kuleuven.rodinia.dsl.rtt.ui.internal.RttStructureActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RttStructureExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RttStructureActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RttStructureActivator.getInstance().getInjector(RttStructureActivator.BE_KULEUVEN_RODINIA_DSL_RTT_RTTSTRUCTURE);
	}
	
}
