/**
 * generated by Xtext
 */
package be.kuleuven.rodinia.dsl.datatypes.validation;

import be.kuleuven.rodinia.dsl.datatypes.validation.AbstractDatatypesValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class DatatypesValidator extends AbstractDatatypesValidator {
}
