/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.rtt.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RttStructureGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class PackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Package");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOrocosPackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOrocosPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTaskContextsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cTaskContextsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cTaskContextsTaskContextParserRuleCall_4_2_0 = (RuleCall)cTaskContextsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cTaskContextsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cTaskContextsTaskContextParserRuleCall_4_3_1_0 = (RuleCall)cTaskContextsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConnectionPoliciesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cConnectionPoliciesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cConnectionPoliciesConnectionPolicyParserRuleCall_5_2_0 = (RuleCall)cConnectionPoliciesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cConnectionPoliciesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cConnectionPoliciesConnectionPolicyParserRuleCall_5_3_1_0 = (RuleCall)cConnectionPoliciesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPeerGroupsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cPeerGroupsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cPeerGroupsPeerGroupParserRuleCall_6_2_0 = (RuleCall)cPeerGroupsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cPeerGroupsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cPeerGroupsPeerGroupParserRuleCall_6_3_1_0 = (RuleCall)cPeerGroupsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Package returns OrocosPackage:
		//	{OrocosPackage} "OrocosPackage" name=EString "{" ("taskContexts" "{" taskContexts+=TaskContext (","
		//	taskContexts+=TaskContext)* "}")? ("connectionPolicies" "{" connectionPolicies+=ConnectionPolicy (","
		//	connectionPolicies+=ConnectionPolicy)* "}")? ("peerGroups" "{" peerGroups+=PeerGroup ("," peerGroups+=PeerGroup)*
		//	"}")? "}";
		public ParserRule getRule() { return rule; }

		//{OrocosPackage} "OrocosPackage" name=EString "{" ("taskContexts" "{" taskContexts+=TaskContext (","
		//taskContexts+=TaskContext)* "}")? ("connectionPolicies" "{" connectionPolicies+=ConnectionPolicy (","
		//connectionPolicies+=ConnectionPolicy)* "}")? ("peerGroups" "{" peerGroups+=PeerGroup ("," peerGroups+=PeerGroup)* "}")?
		//"}"
		public Group getGroup() { return cGroup; }

		//{OrocosPackage}
		public Action getOrocosPackageAction_0() { return cOrocosPackageAction_0; }

		//"OrocosPackage"
		public Keyword getOrocosPackageKeyword_1() { return cOrocosPackageKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("taskContexts" "{" taskContexts+=TaskContext ("," taskContexts+=TaskContext)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"taskContexts"
		public Keyword getTaskContextsKeyword_4_0() { return cTaskContextsKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//taskContexts+=TaskContext
		public Assignment getTaskContextsAssignment_4_2() { return cTaskContextsAssignment_4_2; }

		//TaskContext
		public RuleCall getTaskContextsTaskContextParserRuleCall_4_2_0() { return cTaskContextsTaskContextParserRuleCall_4_2_0; }

		//("," taskContexts+=TaskContext)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//taskContexts+=TaskContext
		public Assignment getTaskContextsAssignment_4_3_1() { return cTaskContextsAssignment_4_3_1; }

		//TaskContext
		public RuleCall getTaskContextsTaskContextParserRuleCall_4_3_1_0() { return cTaskContextsTaskContextParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("connectionPolicies" "{" connectionPolicies+=ConnectionPolicy ("," connectionPolicies+=ConnectionPolicy)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"connectionPolicies"
		public Keyword getConnectionPoliciesKeyword_5_0() { return cConnectionPoliciesKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//connectionPolicies+=ConnectionPolicy
		public Assignment getConnectionPoliciesAssignment_5_2() { return cConnectionPoliciesAssignment_5_2; }

		//ConnectionPolicy
		public RuleCall getConnectionPoliciesConnectionPolicyParserRuleCall_5_2_0() { return cConnectionPoliciesConnectionPolicyParserRuleCall_5_2_0; }

		//("," connectionPolicies+=ConnectionPolicy)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//connectionPolicies+=ConnectionPolicy
		public Assignment getConnectionPoliciesAssignment_5_3_1() { return cConnectionPoliciesAssignment_5_3_1; }

		//ConnectionPolicy
		public RuleCall getConnectionPoliciesConnectionPolicyParserRuleCall_5_3_1_0() { return cConnectionPoliciesConnectionPolicyParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//("peerGroups" "{" peerGroups+=PeerGroup ("," peerGroups+=PeerGroup)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"peerGroups"
		public Keyword getPeerGroupsKeyword_6_0() { return cPeerGroupsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//peerGroups+=PeerGroup
		public Assignment getPeerGroupsAssignment_6_2() { return cPeerGroupsAssignment_6_2; }

		//PeerGroup
		public RuleCall getPeerGroupsPeerGroupParserRuleCall_6_2_0() { return cPeerGroupsPeerGroupParserRuleCall_6_2_0; }

		//("," peerGroups+=PeerGroup)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//peerGroups+=PeerGroup
		public Assignment getPeerGroupsAssignment_6_3_1() { return cPeerGroupsAssignment_6_3_1; }

		//PeerGroup
		public RuleCall getPeerGroupsPeerGroupParserRuleCall_6_3_1_0() { return cPeerGroupsPeerGroupParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class TaskContextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TaskContext");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTaskContextKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNamespaceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNamespaceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNamespaceQualifiedNameWithDotParserRuleCall_4_0 = (RuleCall)cNamespaceAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeQualifiedNameWithDotParserRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cInputPortsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cInputPortsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cInputPortsInputPortParserRuleCall_7_2_0 = (RuleCall)cInputPortsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cInputPortsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cInputPortsInputPortParserRuleCall_7_3_1_0 = (RuleCall)cInputPortsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cOutputPortsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cOutputPortsAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cOutputPortsOutputPortParserRuleCall_8_2_0 = (RuleCall)cOutputPortsAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cOutputPortsAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cOutputPortsOutputPortParserRuleCall_8_3_1_0 = (RuleCall)cOutputPortsAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPropertiesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cPropertiesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cPropertiesPropertyParserRuleCall_9_2_0 = (RuleCall)cPropertiesAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cPropertiesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cPropertiesPropertyParserRuleCall_9_3_1_0 = (RuleCall)cPropertiesAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cOperationsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cOperationsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cOperationsOperationParserRuleCall_10_2_0 = (RuleCall)cOperationsAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cOperationsAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cOperationsOperationParserRuleCall_10_3_1_0 = (RuleCall)cOperationsAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//TaskContext:
		//	"TaskContext" name=EString "{" "namespace" namespace=QualifiedNameWithDot "type" type=QualifiedNameWithDot
		//	("inputPorts" "{" inputPorts+=InputPort ("," inputPorts+=InputPort)* "}")? ("outputPorts" "{" outputPorts+=OutputPort
		//	("," outputPorts+=OutputPort)* "}")? ("properties" "{" properties+=Property ("," properties+=Property)* "}")?
		//	("operations" "{" operations+=Operation ("," operations+=Operation)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"TaskContext" name=EString "{" "namespace" namespace=QualifiedNameWithDot "type" type=QualifiedNameWithDot ("inputPorts"
		//"{" inputPorts+=InputPort ("," inputPorts+=InputPort)* "}")? ("outputPorts" "{" outputPorts+=OutputPort (","
		//outputPorts+=OutputPort)* "}")? ("properties" "{" properties+=Property ("," properties+=Property)* "}")? ("operations"
		//"{" operations+=Operation ("," operations+=Operation)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"TaskContext"
		public Keyword getTaskContextKeyword_0() { return cTaskContextKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"namespace"
		public Keyword getNamespaceKeyword_3() { return cNamespaceKeyword_3; }

		//namespace=QualifiedNameWithDot
		public Assignment getNamespaceAssignment_4() { return cNamespaceAssignment_4; }

		//QualifiedNameWithDot
		public RuleCall getNamespaceQualifiedNameWithDotParserRuleCall_4_0() { return cNamespaceQualifiedNameWithDotParserRuleCall_4_0; }

		//"type"
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }

		//type=QualifiedNameWithDot
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//QualifiedNameWithDot
		public RuleCall getTypeQualifiedNameWithDotParserRuleCall_6_0() { return cTypeQualifiedNameWithDotParserRuleCall_6_0; }

		//("inputPorts" "{" inputPorts+=InputPort ("," inputPorts+=InputPort)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"inputPorts"
		public Keyword getInputPortsKeyword_7_0() { return cInputPortsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//inputPorts+=InputPort
		public Assignment getInputPortsAssignment_7_2() { return cInputPortsAssignment_7_2; }

		//InputPort
		public RuleCall getInputPortsInputPortParserRuleCall_7_2_0() { return cInputPortsInputPortParserRuleCall_7_2_0; }

		//("," inputPorts+=InputPort)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//inputPorts+=InputPort
		public Assignment getInputPortsAssignment_7_3_1() { return cInputPortsAssignment_7_3_1; }

		//InputPort
		public RuleCall getInputPortsInputPortParserRuleCall_7_3_1_0() { return cInputPortsInputPortParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//("outputPorts" "{" outputPorts+=OutputPort ("," outputPorts+=OutputPort)* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"outputPorts"
		public Keyword getOutputPortsKeyword_8_0() { return cOutputPortsKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//outputPorts+=OutputPort
		public Assignment getOutputPortsAssignment_8_2() { return cOutputPortsAssignment_8_2; }

		//OutputPort
		public RuleCall getOutputPortsOutputPortParserRuleCall_8_2_0() { return cOutputPortsOutputPortParserRuleCall_8_2_0; }

		//("," outputPorts+=OutputPort)*
		public Group getGroup_8_3() { return cGroup_8_3; }

		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }

		//outputPorts+=OutputPort
		public Assignment getOutputPortsAssignment_8_3_1() { return cOutputPortsAssignment_8_3_1; }

		//OutputPort
		public RuleCall getOutputPortsOutputPortParserRuleCall_8_3_1_0() { return cOutputPortsOutputPortParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }

		//("properties" "{" properties+=Property ("," properties+=Property)* "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"properties"
		public Keyword getPropertiesKeyword_9_0() { return cPropertiesKeyword_9_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }

		//properties+=Property
		public Assignment getPropertiesAssignment_9_2() { return cPropertiesAssignment_9_2; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_9_2_0() { return cPropertiesPropertyParserRuleCall_9_2_0; }

		//("," properties+=Property)*
		public Group getGroup_9_3() { return cGroup_9_3; }

		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }

		//properties+=Property
		public Assignment getPropertiesAssignment_9_3_1() { return cPropertiesAssignment_9_3_1; }

		//Property
		public RuleCall getPropertiesPropertyParserRuleCall_9_3_1_0() { return cPropertiesPropertyParserRuleCall_9_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }

		//("operations" "{" operations+=Operation ("," operations+=Operation)* "}")?
		public Group getGroup_10() { return cGroup_10; }

		//"operations"
		public Keyword getOperationsKeyword_10_0() { return cOperationsKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//operations+=Operation
		public Assignment getOperationsAssignment_10_2() { return cOperationsAssignment_10_2; }

		//Operation
		public RuleCall getOperationsOperationParserRuleCall_10_2_0() { return cOperationsOperationParserRuleCall_10_2_0; }

		//("," operations+=Operation)*
		public Group getGroup_10_3() { return cGroup_10_3; }

		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }

		//operations+=Operation
		public Assignment getOperationsAssignment_10_3_1() { return cOperationsAssignment_10_3_1; }

		//Operation
		public RuleCall getOperationsOperationParserRuleCall_10_3_1_0() { return cOperationsOperationParserRuleCall_10_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class PeerGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PeerGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPeerGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCoordinatorKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCoordinatorAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cCoordinatorTaskContextCrossReference_4_0 = (CrossReference)cCoordinatorAssignment_4.eContents().get(0);
		private final RuleCall cCoordinatorTaskContextEStringParserRuleCall_4_0_1 = (RuleCall)cCoordinatorTaskContextCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cMembersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cMembersAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cMembersTaskContextCrossReference_5_2_0 = (CrossReference)cMembersAssignment_5_2.eContents().get(0);
		private final RuleCall cMembersTaskContextEStringParserRuleCall_5_2_0_1 = (RuleCall)cMembersTaskContextCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cMembersAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cMembersTaskContextCrossReference_5_3_1_0 = (CrossReference)cMembersAssignment_5_3_1.eContents().get(0);
		private final RuleCall cMembersTaskContextEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cMembersTaskContextCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//PeerGroup:
		//	"PeerGroup" name=EString "{" "coordinator" coordinator=[TaskContext|EString] ("members" "("
		//	members+=[TaskContext|EString] ("," members+=[TaskContext|EString])* ")")? "}";
		public ParserRule getRule() { return rule; }

		//"PeerGroup" name=EString "{" "coordinator" coordinator=[TaskContext|EString] ("members" "("
		//members+=[TaskContext|EString] ("," members+=[TaskContext|EString])* ")")? "}"
		public Group getGroup() { return cGroup; }

		//"PeerGroup"
		public Keyword getPeerGroupKeyword_0() { return cPeerGroupKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"coordinator"
		public Keyword getCoordinatorKeyword_3() { return cCoordinatorKeyword_3; }

		//coordinator=[TaskContext|EString]
		public Assignment getCoordinatorAssignment_4() { return cCoordinatorAssignment_4; }

		//[TaskContext|EString]
		public CrossReference getCoordinatorTaskContextCrossReference_4_0() { return cCoordinatorTaskContextCrossReference_4_0; }

		//EString
		public RuleCall getCoordinatorTaskContextEStringParserRuleCall_4_0_1() { return cCoordinatorTaskContextEStringParserRuleCall_4_0_1; }

		//("members" "(" members+=[TaskContext|EString] ("," members+=[TaskContext|EString])* ")")?
		public Group getGroup_5() { return cGroup_5; }

		//"members"
		public Keyword getMembersKeyword_5_0() { return cMembersKeyword_5_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }

		//members+=[TaskContext|EString]
		public Assignment getMembersAssignment_5_2() { return cMembersAssignment_5_2; }

		//[TaskContext|EString]
		public CrossReference getMembersTaskContextCrossReference_5_2_0() { return cMembersTaskContextCrossReference_5_2_0; }

		//EString
		public RuleCall getMembersTaskContextEStringParserRuleCall_5_2_0_1() { return cMembersTaskContextEStringParserRuleCall_5_2_0_1; }

		//("," members+=[TaskContext|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//members+=[TaskContext|EString]
		public Assignment getMembersAssignment_5_3_1() { return cMembersAssignment_5_3_1; }

		//[TaskContext|EString]
		public CrossReference getMembersTaskContextCrossReference_5_3_1_0() { return cMembersTaskContextCrossReference_5_3_1_0; }

		//EString
		public RuleCall getMembersTaskContextEStringParserRuleCall_5_3_1_0_1() { return cMembersTaskContextEStringParserRuleCall_5_3_1_0_1; }

		//")"
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ConnectionPolicyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConnectionPolicy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectionPolicyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cBufferSizeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cBufferSizeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cBufferSizeEShortParserRuleCall_3_1_0 = (RuleCall)cBufferSizeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLockPolicyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLockPolicyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLockPolicyConnectionPolicyLockPolicyEnumRuleCall_4_1_0 = (RuleCall)cLockPolicyAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTypeConnectionPolicyTypeEnumRuleCall_5_1_0 = (RuleCall)cTypeAssignment_5_1.eContents().get(0);
		private final Keyword cInputPortKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cInputPortAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cInputPortInputPortCrossReference_7_0 = (CrossReference)cInputPortAssignment_7.eContents().get(0);
		private final RuleCall cInputPortInputPortEStringParserRuleCall_7_0_1 = (RuleCall)cInputPortInputPortCrossReference_7_0.eContents().get(1);
		private final Keyword cOutputPortKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cOutputPortAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cOutputPortOutputPortCrossReference_9_0 = (CrossReference)cOutputPortAssignment_9.eContents().get(0);
		private final RuleCall cOutputPortOutputPortEStringParserRuleCall_9_0_1 = (RuleCall)cOutputPortOutputPortCrossReference_9_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//ConnectionPolicy:
		//	"ConnectionPolicy" name=EString "{" ("bufferSize" bufferSize=EShort)? ("lockPolicy"
		//	lockPolicy=ConnectionPolicyLockPolicy)? ("type" type=ConnectionPolicyType)? "inputPort" inputPort=[InputPort|EString]
		//	"outputPort" outputPort=[OutputPort|EString] "}";
		public ParserRule getRule() { return rule; }

		//"ConnectionPolicy" name=EString "{" ("bufferSize" bufferSize=EShort)? ("lockPolicy"
		//lockPolicy=ConnectionPolicyLockPolicy)? ("type" type=ConnectionPolicyType)? "inputPort" inputPort=[InputPort|EString]
		//"outputPort" outputPort=[OutputPort|EString] "}"
		public Group getGroup() { return cGroup; }

		//"ConnectionPolicy"
		public Keyword getConnectionPolicyKeyword_0() { return cConnectionPolicyKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("bufferSize" bufferSize=EShort)?
		public Group getGroup_3() { return cGroup_3; }

		//"bufferSize"
		public Keyword getBufferSizeKeyword_3_0() { return cBufferSizeKeyword_3_0; }

		//bufferSize=EShort
		public Assignment getBufferSizeAssignment_3_1() { return cBufferSizeAssignment_3_1; }

		//EShort
		public RuleCall getBufferSizeEShortParserRuleCall_3_1_0() { return cBufferSizeEShortParserRuleCall_3_1_0; }

		//("lockPolicy" lockPolicy=ConnectionPolicyLockPolicy)?
		public Group getGroup_4() { return cGroup_4; }

		//"lockPolicy"
		public Keyword getLockPolicyKeyword_4_0() { return cLockPolicyKeyword_4_0; }

		//lockPolicy=ConnectionPolicyLockPolicy
		public Assignment getLockPolicyAssignment_4_1() { return cLockPolicyAssignment_4_1; }

		//ConnectionPolicyLockPolicy
		public RuleCall getLockPolicyConnectionPolicyLockPolicyEnumRuleCall_4_1_0() { return cLockPolicyConnectionPolicyLockPolicyEnumRuleCall_4_1_0; }

		//("type" type=ConnectionPolicyType)?
		public Group getGroup_5() { return cGroup_5; }

		//"type"
		public Keyword getTypeKeyword_5_0() { return cTypeKeyword_5_0; }

		//type=ConnectionPolicyType
		public Assignment getTypeAssignment_5_1() { return cTypeAssignment_5_1; }

		//ConnectionPolicyType
		public RuleCall getTypeConnectionPolicyTypeEnumRuleCall_5_1_0() { return cTypeConnectionPolicyTypeEnumRuleCall_5_1_0; }

		//"inputPort"
		public Keyword getInputPortKeyword_6() { return cInputPortKeyword_6; }

		//inputPort=[InputPort|EString]
		public Assignment getInputPortAssignment_7() { return cInputPortAssignment_7; }

		//[InputPort|EString]
		public CrossReference getInputPortInputPortCrossReference_7_0() { return cInputPortInputPortCrossReference_7_0; }

		//EString
		public RuleCall getInputPortInputPortEStringParserRuleCall_7_0_1() { return cInputPortInputPortEStringParserRuleCall_7_0_1; }

		//"outputPort"
		public Keyword getOutputPortKeyword_8() { return cOutputPortKeyword_8; }

		//outputPort=[OutputPort|EString]
		public Assignment getOutputPortAssignment_9() { return cOutputPortAssignment_9; }

		//[OutputPort|EString]
		public CrossReference getOutputPortOutputPortCrossReference_9_0() { return cOutputPortOutputPortCrossReference_9_0; }

		//EString
		public RuleCall getOutputPortOutputPortEStringParserRuleCall_9_0_1() { return cOutputPortOutputPortEStringParserRuleCall_9_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class InputPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InputPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsEventPortAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsEventPortIsEventPortKeyword_0_0 = (Keyword)cIsEventPortAssignment_0.eContents().get(0);
		private final Keyword cInputPortKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDataTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cDataTypeDataTypeCrossReference_4_1_0 = (CrossReference)cDataTypeAssignment_4_1.eContents().get(0);
		private final RuleCall cDataTypeDataTypeQualifiedNameWithDotParserRuleCall_4_1_0_1 = (RuleCall)cDataTypeDataTypeCrossReference_4_1_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInputConnectionPolicyKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cInputConnectionPolicyAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cInputConnectionPolicyConnectionPolicyCrossReference_5_1_0 = (CrossReference)cInputConnectionPolicyAssignment_5_1.eContents().get(0);
		private final RuleCall cInputConnectionPolicyConnectionPolicyEStringParserRuleCall_5_1_0_1 = (RuleCall)cInputConnectionPolicyConnectionPolicyCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//InputPort:
		//	isEventPort?="isEventPort" "InputPort" name=EString "{" ("dataType"
		//	dataType=[datatypes::DataType|QualifiedNameWithDot])? ("inputConnectionPolicy"
		//	inputConnectionPolicy=[ConnectionPolicy|EString])? "}";
		public ParserRule getRule() { return rule; }

		//isEventPort?="isEventPort" "InputPort" name=EString "{" ("dataType"
		//dataType=[datatypes::DataType|QualifiedNameWithDot])? ("inputConnectionPolicy"
		//inputConnectionPolicy=[ConnectionPolicy|EString])? "}"
		public Group getGroup() { return cGroup; }

		//isEventPort?="isEventPort"
		public Assignment getIsEventPortAssignment_0() { return cIsEventPortAssignment_0; }

		//"isEventPort"
		public Keyword getIsEventPortIsEventPortKeyword_0_0() { return cIsEventPortIsEventPortKeyword_0_0; }

		//"InputPort"
		public Keyword getInputPortKeyword_1() { return cInputPortKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("dataType" dataType=[datatypes::DataType|QualifiedNameWithDot])?
		public Group getGroup_4() { return cGroup_4; }

		//"dataType"
		public Keyword getDataTypeKeyword_4_0() { return cDataTypeKeyword_4_0; }

		//dataType=[datatypes::DataType|QualifiedNameWithDot]
		public Assignment getDataTypeAssignment_4_1() { return cDataTypeAssignment_4_1; }

		//[datatypes::DataType|QualifiedNameWithDot]
		public CrossReference getDataTypeDataTypeCrossReference_4_1_0() { return cDataTypeDataTypeCrossReference_4_1_0; }

		//QualifiedNameWithDot
		public RuleCall getDataTypeDataTypeQualifiedNameWithDotParserRuleCall_4_1_0_1() { return cDataTypeDataTypeQualifiedNameWithDotParserRuleCall_4_1_0_1; }

		//("inputConnectionPolicy" inputConnectionPolicy=[ConnectionPolicy|EString])?
		public Group getGroup_5() { return cGroup_5; }

		//"inputConnectionPolicy"
		public Keyword getInputConnectionPolicyKeyword_5_0() { return cInputConnectionPolicyKeyword_5_0; }

		//inputConnectionPolicy=[ConnectionPolicy|EString]
		public Assignment getInputConnectionPolicyAssignment_5_1() { return cInputConnectionPolicyAssignment_5_1; }

		//[ConnectionPolicy|EString]
		public CrossReference getInputConnectionPolicyConnectionPolicyCrossReference_5_1_0() { return cInputConnectionPolicyConnectionPolicyCrossReference_5_1_0; }

		//EString
		public RuleCall getInputConnectionPolicyConnectionPolicyEStringParserRuleCall_5_1_0_1() { return cInputConnectionPolicyConnectionPolicyEStringParserRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class OutputPortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OutputPort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOutputPortKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDataTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDataTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cDataTypeDataTypeCrossReference_3_1_0 = (CrossReference)cDataTypeAssignment_3_1.eContents().get(0);
		private final RuleCall cDataTypeDataTypeQualifiedNameWithDotParserRuleCall_3_1_0_1 = (RuleCall)cDataTypeDataTypeCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOutputConnectionPolicyKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOutputConnectionPolicyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cOutputConnectionPolicyConnectionPolicyCrossReference_4_1_0 = (CrossReference)cOutputConnectionPolicyAssignment_4_1.eContents().get(0);
		private final RuleCall cOutputConnectionPolicyConnectionPolicyEStringParserRuleCall_4_1_0_1 = (RuleCall)cOutputConnectionPolicyConnectionPolicyCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//OutputPort:
		//	"OutputPort" name=EString "{" ("dataType" dataType=[datatypes::DataType|QualifiedNameWithDot])?
		//	("outputConnectionPolicy" outputConnectionPolicy=[ConnectionPolicy|EString])? "}";
		public ParserRule getRule() { return rule; }

		//"OutputPort" name=EString "{" ("dataType" dataType=[datatypes::DataType|QualifiedNameWithDot])?
		//("outputConnectionPolicy" outputConnectionPolicy=[ConnectionPolicy|EString])? "}"
		public Group getGroup() { return cGroup; }

		//"OutputPort"
		public Keyword getOutputPortKeyword_0() { return cOutputPortKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("dataType" dataType=[datatypes::DataType|QualifiedNameWithDot])?
		public Group getGroup_3() { return cGroup_3; }

		//"dataType"
		public Keyword getDataTypeKeyword_3_0() { return cDataTypeKeyword_3_0; }

		//dataType=[datatypes::DataType|QualifiedNameWithDot]
		public Assignment getDataTypeAssignment_3_1() { return cDataTypeAssignment_3_1; }

		//[datatypes::DataType|QualifiedNameWithDot]
		public CrossReference getDataTypeDataTypeCrossReference_3_1_0() { return cDataTypeDataTypeCrossReference_3_1_0; }

		//QualifiedNameWithDot
		public RuleCall getDataTypeDataTypeQualifiedNameWithDotParserRuleCall_3_1_0_1() { return cDataTypeDataTypeQualifiedNameWithDotParserRuleCall_3_1_0_1; }

		//("outputConnectionPolicy" outputConnectionPolicy=[ConnectionPolicy|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"outputConnectionPolicy"
		public Keyword getOutputConnectionPolicyKeyword_4_0() { return cOutputConnectionPolicyKeyword_4_0; }

		//outputConnectionPolicy=[ConnectionPolicy|EString]
		public Assignment getOutputConnectionPolicyAssignment_4_1() { return cOutputConnectionPolicyAssignment_4_1; }

		//[ConnectionPolicy|EString]
		public CrossReference getOutputConnectionPolicyConnectionPolicyCrossReference_4_1_0() { return cOutputConnectionPolicyConnectionPolicyCrossReference_4_1_0; }

		//EString
		public RuleCall getOutputConnectionPolicyConnectionPolicyEStringParserRuleCall_4_1_0_1() { return cOutputConnectionPolicyConnectionPolicyEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPropertyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValueKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValueAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_5_1_0 = (RuleCall)cValueAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cTypeDataTypeCrossReference_6_1_0 = (CrossReference)cTypeAssignment_6_1.eContents().get(0);
		private final RuleCall cTypeDataTypeQualifiedNameWithDotParserRuleCall_6_1_0_1 = (RuleCall)cTypeDataTypeCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Property:
		//	{Property} "Property" name=EString "{" ("description" description=EString)? ("value" value=EString)? ("type"
		//	type=[datatypes::DataType|QualifiedNameWithDot])? "}";
		public ParserRule getRule() { return rule; }

		//{Property} "Property" name=EString "{" ("description" description=EString)? ("value" value=EString)? ("type"
		//type=[datatypes::DataType|QualifiedNameWithDot])? "}"
		public Group getGroup() { return cGroup; }

		//{Property}
		public Action getPropertyAction_0() { return cPropertyAction_0; }

		//"Property"
		public Keyword getPropertyKeyword_1() { return cPropertyKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("description" description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//("value" value=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"value"
		public Keyword getValueKeyword_5_0() { return cValueKeyword_5_0; }

		//value=EString
		public Assignment getValueAssignment_5_1() { return cValueAssignment_5_1; }

		//EString
		public RuleCall getValueEStringParserRuleCall_5_1_0() { return cValueEStringParserRuleCall_5_1_0; }

		//("type" type=[datatypes::DataType|QualifiedNameWithDot])?
		public Group getGroup_6() { return cGroup_6; }

		//"type"
		public Keyword getTypeKeyword_6_0() { return cTypeKeyword_6_0; }

		//type=[datatypes::DataType|QualifiedNameWithDot]
		public Assignment getTypeAssignment_6_1() { return cTypeAssignment_6_1; }

		//[datatypes::DataType|QualifiedNameWithDot]
		public CrossReference getTypeDataTypeCrossReference_6_1_0() { return cTypeDataTypeCrossReference_6_1_0; }

		//QualifiedNameWithDot
		public RuleCall getTypeDataTypeQualifiedNameWithDotParserRuleCall_6_1_0_1() { return cTypeDataTypeQualifiedNameWithDotParserRuleCall_6_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOperationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDocumentationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDocumentationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDocumentationEStringParserRuleCall_4_1_0 = (RuleCall)cDocumentationAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReturnTypeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cReturnTypeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cReturnTypeDataTypeCrossReference_5_1_0 = (CrossReference)cReturnTypeAssignment_5_1.eContents().get(0);
		private final RuleCall cReturnTypeDataTypeQualifiedNameWithDotParserRuleCall_5_1_0_1 = (RuleCall)cReturnTypeDataTypeCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Operation:
		//	{Operation} "Operation" name=EString "{" ("documentation" documentation=EString)? ("returnType"
		//	returnType=[datatypes::DataType|QualifiedNameWithDot])? "}";
		public ParserRule getRule() { return rule; }

		//{Operation} "Operation" name=EString "{" ("documentation" documentation=EString)? ("returnType"
		//returnType=[datatypes::DataType|QualifiedNameWithDot])? "}"
		public Group getGroup() { return cGroup; }

		//{Operation}
		public Action getOperationAction_0() { return cOperationAction_0; }

		//"Operation"
		public Keyword getOperationKeyword_1() { return cOperationKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("documentation" documentation=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"documentation"
		public Keyword getDocumentationKeyword_4_0() { return cDocumentationKeyword_4_0; }

		//documentation=EString
		public Assignment getDocumentationAssignment_4_1() { return cDocumentationAssignment_4_1; }

		//EString
		public RuleCall getDocumentationEStringParserRuleCall_4_1_0() { return cDocumentationEStringParserRuleCall_4_1_0; }

		//("returnType" returnType=[datatypes::DataType|QualifiedNameWithDot])?
		public Group getGroup_5() { return cGroup_5; }

		//"returnType"
		public Keyword getReturnTypeKeyword_5_0() { return cReturnTypeKeyword_5_0; }

		//returnType=[datatypes::DataType|QualifiedNameWithDot]
		public Assignment getReturnTypeAssignment_5_1() { return cReturnTypeAssignment_5_1; }

		//[datatypes::DataType|QualifiedNameWithDot]
		public CrossReference getReturnTypeDataTypeCrossReference_5_1_0() { return cReturnTypeDataTypeCrossReference_5_1_0; }

		//QualifiedNameWithDot
		public RuleCall getReturnTypeDataTypeQualifiedNameWithDotParserRuleCall_5_1_0_1() { return cReturnTypeDataTypeQualifiedNameWithDotParserRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EShortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EShort");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EShort returns ecore::EShort:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class IActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IActivity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cActivityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSlaveParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//IActivity:
		//	Activity | Slave;
		public ParserRule getRule() { return rule; }

		//Activity | Slave
		public Alternatives getAlternatives() { return cAlternatives; }

		//Activity
		public RuleCall getActivityParserRuleCall_0() { return cActivityParserRuleCall_0; }

		//Slave
		public RuleCall getSlaveParserRuleCall_1() { return cSlaveParserRuleCall_1; }
	}

	public class ActivityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Activity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActivityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSchedulerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSchedulerAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSchedulerSchedulerEnumRuleCall_4_0 = (RuleCall)cSchedulerAssignment_4.eContents().get(0);
		private final Keyword cCpuAffinityKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCpuAffinityAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCpuAffinityEStringParserRuleCall_6_0 = (RuleCall)cCpuAffinityAssignment_6.eContents().get(0);
		private final Keyword cPeriodKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPeriodAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPeriodEFloatParserRuleCall_8_0 = (RuleCall)cPeriodAssignment_8.eContents().get(0);
		private final Keyword cPriorityKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cPriorityAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cPriorityEIntParserRuleCall_10_0 = (RuleCall)cPriorityAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cTaskContextKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cTaskContextAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final CrossReference cTaskContextTaskContextCrossReference_11_1_0 = (CrossReference)cTaskContextAssignment_11_1.eContents().get(0);
		private final RuleCall cTaskContextTaskContextEStringParserRuleCall_11_1_0_1 = (RuleCall)cTaskContextTaskContextCrossReference_11_1_0.eContents().get(1);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cSlaveKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cSlaveAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cSlaveSlaveParserRuleCall_12_2_0 = (RuleCall)cSlaveAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cSlaveAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cSlaveSlaveParserRuleCall_12_3_1_0 = (RuleCall)cSlaveAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Activity:
		//	"Activity" name=EString "{" "scheduler" scheduler=Scheduler "cpuAffinity" cpuAffinity=EString "period" period=EFloat
		//	"priority" priority=EInt ("taskContext" taskContext=[TaskContext|EString])? ("slave" "{" slave+=Slave (","
		//	slave+=Slave)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"Activity" name=EString "{" "scheduler" scheduler=Scheduler "cpuAffinity" cpuAffinity=EString "period" period=EFloat
		//"priority" priority=EInt ("taskContext" taskContext=[TaskContext|EString])? ("slave" "{" slave+=Slave (","
		//slave+=Slave)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Activity"
		public Keyword getActivityKeyword_0() { return cActivityKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"scheduler"
		public Keyword getSchedulerKeyword_3() { return cSchedulerKeyword_3; }

		//scheduler=Scheduler
		public Assignment getSchedulerAssignment_4() { return cSchedulerAssignment_4; }

		//Scheduler
		public RuleCall getSchedulerSchedulerEnumRuleCall_4_0() { return cSchedulerSchedulerEnumRuleCall_4_0; }

		//"cpuAffinity"
		public Keyword getCpuAffinityKeyword_5() { return cCpuAffinityKeyword_5; }

		//cpuAffinity=EString
		public Assignment getCpuAffinityAssignment_6() { return cCpuAffinityAssignment_6; }

		//EString
		public RuleCall getCpuAffinityEStringParserRuleCall_6_0() { return cCpuAffinityEStringParserRuleCall_6_0; }

		//"period"
		public Keyword getPeriodKeyword_7() { return cPeriodKeyword_7; }

		//period=EFloat
		public Assignment getPeriodAssignment_8() { return cPeriodAssignment_8; }

		//EFloat
		public RuleCall getPeriodEFloatParserRuleCall_8_0() { return cPeriodEFloatParserRuleCall_8_0; }

		//"priority"
		public Keyword getPriorityKeyword_9() { return cPriorityKeyword_9; }

		//priority=EInt
		public Assignment getPriorityAssignment_10() { return cPriorityAssignment_10; }

		//EInt
		public RuleCall getPriorityEIntParserRuleCall_10_0() { return cPriorityEIntParserRuleCall_10_0; }

		//("taskContext" taskContext=[TaskContext|EString])?
		public Group getGroup_11() { return cGroup_11; }

		//"taskContext"
		public Keyword getTaskContextKeyword_11_0() { return cTaskContextKeyword_11_0; }

		//taskContext=[TaskContext|EString]
		public Assignment getTaskContextAssignment_11_1() { return cTaskContextAssignment_11_1; }

		//[TaskContext|EString]
		public CrossReference getTaskContextTaskContextCrossReference_11_1_0() { return cTaskContextTaskContextCrossReference_11_1_0; }

		//EString
		public RuleCall getTaskContextTaskContextEStringParserRuleCall_11_1_0_1() { return cTaskContextTaskContextEStringParserRuleCall_11_1_0_1; }

		//("slave" "{" slave+=Slave ("," slave+=Slave)* "}")?
		public Group getGroup_12() { return cGroup_12; }

		//"slave"
		public Keyword getSlaveKeyword_12_0() { return cSlaveKeyword_12_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }

		//slave+=Slave
		public Assignment getSlaveAssignment_12_2() { return cSlaveAssignment_12_2; }

		//Slave
		public RuleCall getSlaveSlaveParserRuleCall_12_2_0() { return cSlaveSlaveParserRuleCall_12_2_0; }

		//("," slave+=Slave)*
		public Group getGroup_12_3() { return cGroup_12_3; }

		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }

		//slave+=Slave
		public Assignment getSlaveAssignment_12_3_1() { return cSlaveAssignment_12_3_1; }

		//Slave
		public RuleCall getSlaveSlaveParserRuleCall_12_3_1_0() { return cSlaveSlaveParserRuleCall_12_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class SlaveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Slave");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cSlaveAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSlaveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTaskContextKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTaskContextAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cTaskContextTaskContextCrossReference_4_1_0 = (CrossReference)cTaskContextAssignment_4_1.eContents().get(0);
		private final RuleCall cTaskContextTaskContextEStringParserRuleCall_4_1_0_1 = (RuleCall)cTaskContextTaskContextCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Slave:
		//	{Slave} "Slave" name=EString "{" ("taskContext" taskContext=[TaskContext|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Slave} "Slave" name=EString "{" ("taskContext" taskContext=[TaskContext|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Slave}
		public Action getSlaveAction_0() { return cSlaveAction_0; }

		//"Slave"
		public Keyword getSlaveKeyword_1() { return cSlaveKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("taskContext" taskContext=[TaskContext|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"taskContext"
		public Keyword getTaskContextKeyword_4_0() { return cTaskContextKeyword_4_0; }

		//taskContext=[TaskContext|EString]
		public Assignment getTaskContextAssignment_4_1() { return cTaskContextAssignment_4_1; }

		//[TaskContext|EString]
		public CrossReference getTaskContextTaskContextCrossReference_4_1_0() { return cTaskContextTaskContextCrossReference_4_1_0; }

		//EString
		public RuleCall getTaskContextTaskContextEStringParserRuleCall_4_1_0_1() { return cTaskContextTaskContextEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_4() { return cGroup_4; }

		//"E" | "e"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"E"
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }

		//"e"
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cColonColonKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("::" ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("::" ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("::" ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"::"
		public Keyword getColonColonKeyword_1_0() { return cColonColonKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class QualifiedNameWithDotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedNameWithDot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedNameWithDot:
		//	QualifiedName ("." ID)*;
		public ParserRule getRule() { return rule; }

		//QualifiedName ("." ID)*
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	public class ConnectionPolicyLockPolicyElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ConnectionPolicyLockPolicy");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cUNSYNCEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cUNSYNCUNSYNCKeyword_0_0 = (Keyword)cUNSYNCEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLOCKEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLOCKEDLOCKEDKeyword_1_0 = (Keyword)cLOCKEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLOCK_FREEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLOCK_FREELOCK_FREEKeyword_2_0 = (Keyword)cLOCK_FREEEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ConnectionPolicyLockPolicy:
		//	UNSYNC | LOCKED | LOCK_FREE;
		public EnumRule getRule() { return rule; }

		//UNSYNC | LOCKED | LOCK_FREE
		public Alternatives getAlternatives() { return cAlternatives; }

		//UNSYNC
		public EnumLiteralDeclaration getUNSYNCEnumLiteralDeclaration_0() { return cUNSYNCEnumLiteralDeclaration_0; }

		//"UNSYNC"
		public Keyword getUNSYNCUNSYNCKeyword_0_0() { return cUNSYNCUNSYNCKeyword_0_0; }

		//LOCKED
		public EnumLiteralDeclaration getLOCKEDEnumLiteralDeclaration_1() { return cLOCKEDEnumLiteralDeclaration_1; }

		//"LOCKED"
		public Keyword getLOCKEDLOCKEDKeyword_1_0() { return cLOCKEDLOCKEDKeyword_1_0; }

		//LOCK_FREE
		public EnumLiteralDeclaration getLOCK_FREEEnumLiteralDeclaration_2() { return cLOCK_FREEEnumLiteralDeclaration_2; }

		//"LOCK_FREE"
		public Keyword getLOCK_FREELOCK_FREEKeyword_2_0() { return cLOCK_FREELOCK_FREEKeyword_2_0; }
	}

	public class ConnectionPolicyTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "ConnectionPolicyType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDATAEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDATADATAKeyword_0_0 = (Keyword)cDATAEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBUFFEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBUFFERBUFFERKeyword_1_0 = (Keyword)cBUFFEREnumLiteralDeclaration_1.eContents().get(0);
		
		//enum ConnectionPolicyType:
		//	DATA | BUFFER;
		public EnumRule getRule() { return rule; }

		//DATA | BUFFER
		public Alternatives getAlternatives() { return cAlternatives; }

		//DATA
		public EnumLiteralDeclaration getDATAEnumLiteralDeclaration_0() { return cDATAEnumLiteralDeclaration_0; }

		//"DATA"
		public Keyword getDATADATAKeyword_0_0() { return cDATADATAKeyword_0_0; }

		//BUFFER
		public EnumLiteralDeclaration getBUFFEREnumLiteralDeclaration_1() { return cBUFFEREnumLiteralDeclaration_1; }

		//"BUFFER"
		public Keyword getBUFFERBUFFERKeyword_1_0() { return cBUFFERBUFFERKeyword_1_0; }
	}

	public class SchedulerElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Scheduler");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cORO_SCHED_OTHEREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cORO_SCHED_OTHERORO_SCHED_OTHERKeyword_0_0 = (Keyword)cORO_SCHED_OTHEREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cORO_SCHED_RTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cORO_SCHED_RTORO_SCHED_RTKeyword_1_0 = (Keyword)cORO_SCHED_RTEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Scheduler:
		//	ORO_SCHED_OTHER | ORO_SCHED_RT;
		public EnumRule getRule() { return rule; }

		//ORO_SCHED_OTHER | ORO_SCHED_RT
		public Alternatives getAlternatives() { return cAlternatives; }

		//ORO_SCHED_OTHER
		public EnumLiteralDeclaration getORO_SCHED_OTHEREnumLiteralDeclaration_0() { return cORO_SCHED_OTHEREnumLiteralDeclaration_0; }

		//"ORO_SCHED_OTHER"
		public Keyword getORO_SCHED_OTHERORO_SCHED_OTHERKeyword_0_0() { return cORO_SCHED_OTHERORO_SCHED_OTHERKeyword_0_0; }

		//ORO_SCHED_RT
		public EnumLiteralDeclaration getORO_SCHED_RTEnumLiteralDeclaration_1() { return cORO_SCHED_RTEnumLiteralDeclaration_1; }

		//"ORO_SCHED_RT"
		public Keyword getORO_SCHED_RTORO_SCHED_RTKeyword_1_0() { return cORO_SCHED_RTORO_SCHED_RTKeyword_1_0; }
	}
	
	private PackageElements pPackage;
	private TaskContextElements pTaskContext;
	private PeerGroupElements pPeerGroup;
	private ConnectionPolicyElements pConnectionPolicy;
	private InputPortElements pInputPort;
	private OutputPortElements pOutputPort;
	private PropertyElements pProperty;
	private OperationElements pOperation;
	private EShortElements pEShort;
	private ConnectionPolicyLockPolicyElements unknownRuleConnectionPolicyLockPolicy;
	private ConnectionPolicyTypeElements unknownRuleConnectionPolicyType;
	private IActivityElements pIActivity;
	private ActivityElements pActivity;
	private SlaveElements pSlave;
	private SchedulerElements unknownRuleScheduler;
	private EStringElements pEString;
	private EFloatElements pEFloat;
	private EIntElements pEInt;
	private QualifiedNameElements pQualifiedName;
	private QualifiedNameWithDotElements pQualifiedNameWithDot;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public RttStructureGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("be.kuleuven.rodinia.dsl.rtt.RttStructure".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Package returns OrocosPackage:
	//	{OrocosPackage} "OrocosPackage" name=EString "{" ("taskContexts" "{" taskContexts+=TaskContext (","
	//	taskContexts+=TaskContext)* "}")? ("connectionPolicies" "{" connectionPolicies+=ConnectionPolicy (","
	//	connectionPolicies+=ConnectionPolicy)* "}")? ("peerGroups" "{" peerGroups+=PeerGroup ("," peerGroups+=PeerGroup)*
	//	"}")? "}";
	public PackageElements getPackageAccess() {
		return (pPackage != null) ? pPackage : (pPackage = new PackageElements());
	}
	
	public ParserRule getPackageRule() {
		return getPackageAccess().getRule();
	}

	//TaskContext:
	//	"TaskContext" name=EString "{" "namespace" namespace=QualifiedNameWithDot "type" type=QualifiedNameWithDot
	//	("inputPorts" "{" inputPorts+=InputPort ("," inputPorts+=InputPort)* "}")? ("outputPorts" "{" outputPorts+=OutputPort
	//	("," outputPorts+=OutputPort)* "}")? ("properties" "{" properties+=Property ("," properties+=Property)* "}")?
	//	("operations" "{" operations+=Operation ("," operations+=Operation)* "}")? "}";
	public TaskContextElements getTaskContextAccess() {
		return (pTaskContext != null) ? pTaskContext : (pTaskContext = new TaskContextElements());
	}
	
	public ParserRule getTaskContextRule() {
		return getTaskContextAccess().getRule();
	}

	//PeerGroup:
	//	"PeerGroup" name=EString "{" "coordinator" coordinator=[TaskContext|EString] ("members" "("
	//	members+=[TaskContext|EString] ("," members+=[TaskContext|EString])* ")")? "}";
	public PeerGroupElements getPeerGroupAccess() {
		return (pPeerGroup != null) ? pPeerGroup : (pPeerGroup = new PeerGroupElements());
	}
	
	public ParserRule getPeerGroupRule() {
		return getPeerGroupAccess().getRule();
	}

	//ConnectionPolicy:
	//	"ConnectionPolicy" name=EString "{" ("bufferSize" bufferSize=EShort)? ("lockPolicy"
	//	lockPolicy=ConnectionPolicyLockPolicy)? ("type" type=ConnectionPolicyType)? "inputPort" inputPort=[InputPort|EString]
	//	"outputPort" outputPort=[OutputPort|EString] "}";
	public ConnectionPolicyElements getConnectionPolicyAccess() {
		return (pConnectionPolicy != null) ? pConnectionPolicy : (pConnectionPolicy = new ConnectionPolicyElements());
	}
	
	public ParserRule getConnectionPolicyRule() {
		return getConnectionPolicyAccess().getRule();
	}

	//InputPort:
	//	isEventPort?="isEventPort" "InputPort" name=EString "{" ("dataType"
	//	dataType=[datatypes::DataType|QualifiedNameWithDot])? ("inputConnectionPolicy"
	//	inputConnectionPolicy=[ConnectionPolicy|EString])? "}";
	public InputPortElements getInputPortAccess() {
		return (pInputPort != null) ? pInputPort : (pInputPort = new InputPortElements());
	}
	
	public ParserRule getInputPortRule() {
		return getInputPortAccess().getRule();
	}

	//OutputPort:
	//	"OutputPort" name=EString "{" ("dataType" dataType=[datatypes::DataType|QualifiedNameWithDot])?
	//	("outputConnectionPolicy" outputConnectionPolicy=[ConnectionPolicy|EString])? "}";
	public OutputPortElements getOutputPortAccess() {
		return (pOutputPort != null) ? pOutputPort : (pOutputPort = new OutputPortElements());
	}
	
	public ParserRule getOutputPortRule() {
		return getOutputPortAccess().getRule();
	}

	//Property:
	//	{Property} "Property" name=EString "{" ("description" description=EString)? ("value" value=EString)? ("type"
	//	type=[datatypes::DataType|QualifiedNameWithDot])? "}";
	public PropertyElements getPropertyAccess() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//Operation:
	//	{Operation} "Operation" name=EString "{" ("documentation" documentation=EString)? ("returnType"
	//	returnType=[datatypes::DataType|QualifiedNameWithDot])? "}";
	public OperationElements getOperationAccess() {
		return (pOperation != null) ? pOperation : (pOperation = new OperationElements());
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}

	//EShort returns ecore::EShort:
	//	"-"? INT;
	public EShortElements getEShortAccess() {
		return (pEShort != null) ? pEShort : (pEShort = new EShortElements());
	}
	
	public ParserRule getEShortRule() {
		return getEShortAccess().getRule();
	}

	//enum ConnectionPolicyLockPolicy:
	//	UNSYNC | LOCKED | LOCK_FREE;
	public ConnectionPolicyLockPolicyElements getConnectionPolicyLockPolicyAccess() {
		return (unknownRuleConnectionPolicyLockPolicy != null) ? unknownRuleConnectionPolicyLockPolicy : (unknownRuleConnectionPolicyLockPolicy = new ConnectionPolicyLockPolicyElements());
	}
	
	public EnumRule getConnectionPolicyLockPolicyRule() {
		return getConnectionPolicyLockPolicyAccess().getRule();
	}

	//enum ConnectionPolicyType:
	//	DATA | BUFFER;
	public ConnectionPolicyTypeElements getConnectionPolicyTypeAccess() {
		return (unknownRuleConnectionPolicyType != null) ? unknownRuleConnectionPolicyType : (unknownRuleConnectionPolicyType = new ConnectionPolicyTypeElements());
	}
	
	public EnumRule getConnectionPolicyTypeRule() {
		return getConnectionPolicyTypeAccess().getRule();
	}

	//IActivity:
	//	Activity | Slave;
	public IActivityElements getIActivityAccess() {
		return (pIActivity != null) ? pIActivity : (pIActivity = new IActivityElements());
	}
	
	public ParserRule getIActivityRule() {
		return getIActivityAccess().getRule();
	}

	//Activity:
	//	"Activity" name=EString "{" "scheduler" scheduler=Scheduler "cpuAffinity" cpuAffinity=EString "period" period=EFloat
	//	"priority" priority=EInt ("taskContext" taskContext=[TaskContext|EString])? ("slave" "{" slave+=Slave (","
	//	slave+=Slave)* "}")? "}";
	public ActivityElements getActivityAccess() {
		return (pActivity != null) ? pActivity : (pActivity = new ActivityElements());
	}
	
	public ParserRule getActivityRule() {
		return getActivityAccess().getRule();
	}

	//Slave:
	//	{Slave} "Slave" name=EString "{" ("taskContext" taskContext=[TaskContext|EString])? "}";
	public SlaveElements getSlaveAccess() {
		return (pSlave != null) ? pSlave : (pSlave = new SlaveElements());
	}
	
	public ParserRule getSlaveRule() {
		return getSlaveAccess().getRule();
	}

	//enum Scheduler:
	//	ORO_SCHED_OTHER | ORO_SCHED_RT;
	public SchedulerElements getSchedulerAccess() {
		return (unknownRuleScheduler != null) ? unknownRuleScheduler : (unknownRuleScheduler = new SchedulerElements());
	}
	
	public EnumRule getSchedulerRule() {
		return getSchedulerAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EFloat returns ecore::EFloat:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public EFloatElements getEFloatAccess() {
		return (pEFloat != null) ? pEFloat : (pEFloat = new EFloatElements());
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return (pEInt != null) ? pEInt : (pEInt = new EIntElements());
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//QualifiedName:
	//	ID ("::" ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//QualifiedNameWithDot:
	//	QualifiedName ("." ID)*;
	public QualifiedNameWithDotElements getQualifiedNameWithDotAccess() {
		return (pQualifiedNameWithDot != null) ? pQualifiedNameWithDot : (pQualifiedNameWithDot = new QualifiedNameWithDotElements());
	}
	
	public ParserRule getQualifiedNameWithDotRule() {
		return getQualifiedNameWithDotAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
