/*
* generated by Xtext
*/
package cz.cuni.mff.d3s.dsl.deeco;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DEECoDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return cz.cuni.mff.d3s.dsl.deeco.ui.internal.DEECoDslActivator.getInstance().getInjector("cz.cuni.mff.d3s.dsl.deeco.DEECoDsl");
	}
	
}
