<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rtt" nsURI="be.kueleuven.rodinia.model.rtt" nsPrefix="rtt">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="be.kueleuven.rodinia.model"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="OrocosPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskContexts" upperBound="-1"
        eType="#//TaskContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionPolicies" upperBound="-1"
        eType="#//ConnectionPolicy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//InputPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//OutputPort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEventPort" unique="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="ecore:EClass ../../be.kuleuven.rodinia.dsl.datatypes/src-gen/be/kuleuven/rodinia/dsl/datatypes/Datatypes.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputConnectionPolicy"
        eType="#//ConnectionPolicy" eOpposite="#//ConnectionPolicy/inputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="ecore:EClass ../../be.kuleuven.rodinia.dsl.datatypes/src-gen/be/kuleuven/rodinia/dsl/datatypes/Datatypes.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputConnectionPolicy"
        eType="#//ConnectionPolicy" eOpposite="#//ConnectionPolicy/outputPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPolicy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPort" lowerBound="1"
        eType="#//InputPort" eOpposite="#//InputPort/inputConnectionPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPort" lowerBound="1"
        eType="#//OutputPort" eOpposite="#//OutputPort/outputConnectionPolicy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferSize" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockPolicy" unique="false"
        eType="#//ConnectionPolicyLockPolicy" defaultValueLiteral="LOCK_FREE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//ConnectionPolicyType"
        defaultValueLiteral="DATA"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionPolicyType">
    <eLiterals name="DATA"/>
    <eLiterals name="BUFFER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionPolicyLockPolicy">
    <eLiterals name="UNSYNC"/>
    <eLiterals name="LOCKED" value="1"/>
    <eLiterals name="LOCK_FREE" value="2"/>
  </eClassifiers>
</ecore:EPackage>
