/*
* generated by Xtext
*/
package be.kuleuven.rodinia.dsl.rtt.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import be.kuleuven.rodinia.dsl.rtt.services.RttDslGrammarAccess;

public class RttDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RttDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected be.kuleuven.rodinia.dsl.rtt.parser.antlr.internal.InternalRttDslParser createParser(XtextTokenStream stream) {
		return new be.kuleuven.rodinia.dsl.rtt.parser.antlr.internal.InternalRttDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "OrocosPackage";
	}
	
	public RttDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RttDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
